version: "3.9"


services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
  #    PGDATA: "/var/lib/postgresql/data/pgdata"
  #  volumes:
   #   - habrdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#volumes:
#  habrdb-data: